/*eslint-disable*/
import React from "react";
import s from './PhotosMap.module.css';

export default function PhotosMap() {
  return (
    <div className={s.photosMap}>
      <div className={s.photos}>
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
        <img src={require("assets/img/Аксенин_Василь_Степанович.jpg").default} alt="..." />
      </div>
    </div>
  );
}
